estimator:
  - name: age-extractor
    params: {}
  - name: categorical-encoder
    params:
      one_hot: true
      force_dense_array: true
  - name: standard-scaler
    params: {}
  - name: linear-regressor
    params: {}

data:
  filepath: ./dataset.csv

metrics:
  - name: mean absolute error
    params: {}

search:
  jobs: -1
  grid:
    - name: random-forest-regressor
      params:
        n_estimators: [50, 100, 200]
        max_depth: [null, 10, 20, 30, 60]

export:
  output_dir: ./models

reports:
  dir: ./reports